[mypy]
plugins = mypy_django_plugin.main
# Enable strict type checking gradually
follow_imports = skip
check_untyped_defs = false
warn_unused_ignores = false
no_implicit_optional = false
strict_optional = false
disallow_untyped_defs = false
disallow_any_unimported = false
warn_return_any = false
# Optional: ignore missing imports for third-party libs
ignore_missing_imports = True


# Point to your Django settings module
[mypy.plugins.django-stubs]
django_settings_module = Carpool_System.settings.dev
# Enable strict settings for models
strict_settings = True


[mypy-requests.*]
ignore_missing_imports = True
