# Generated by Django 5.0.3 on 2025-04-01 23:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ride",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modeified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("departure_town", models.CharField(max_length=100)),
                ("arrival_town", models.CharField(max_length=100)),
                ("departure_datetime", models.DateTimeField()),
                (
                    "available_seats",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                message="You cant create a ride with less that 1 seat available",
                            )
                        ],
                    ),
                ),
                ("price_per_seat", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RideAlert",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modeified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("departure_town", models.CharField(max_length=100)),
                ("arrival_town", models.CharField(max_length=100)),
                ("departure_datetime", models.DateTimeField()),
                (
                    "available_seats",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                message="You cant create an alert for a ride with less that 1 seat available",
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RideRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modeified_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("departure_town", models.CharField(max_length=100)),
                ("arrival_town", models.CharField(max_length=100)),
                ("departure_datetime", models.DateTimeField()),
                (
                    "required_seats",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                message="You cant create a request with less that one required seat",
                            )
                        ],
                    ),
                ),
                ("price_per_seat", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
