# Generated by Django 5.0.3 on 2025-04-01 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides_and_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="available_seats",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="You cant create a ride with less that 1 seat available",
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="ridealert",
            name="available_seats",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="You cant create an alert for a ride with less that 1 seat available",
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="required_seats",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="You cant create a request with less that one required seat",
                    )
                ]
            ),
        ),
    ]
