# Generated by Django 5.0.3 on 2025-04-02 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides_and_requests", "0003_alter_ride_available_seats_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ride",
            name="available_seats",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="ridealert",
            name="available_seats",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="required_seats",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
