# Generated by Django 5.0.3 on 2025-04-07 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rides_and_requests", "0005_alter_ride_available_seats_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ride",
            old_name="modeified_at",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="ridealert",
            old_name="modeified_at",
            new_name="modified_at",
        ),
        migrations.RenameField(
            model_name="riderequest",
            old_name="modeified_at",
            new_name="modified_at",
        ),
    ]
