# Generated by Django 5.0.3 on 2025-04-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rides", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="is_full",
            field=models.BooleanField(default=False),
        ),
    ]
