# Generated by Django 5.2.12 on 2026-03-11 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0002_alter_reservation_payment_status_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="ride",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="ridealert",
            old_name="modified_at",
            new_name="updated_at",
        ),
        migrations.RenameField(
            model_name="riderequest",
            old_name="modified_at",
            new_name="updated_at",
        ),
    ]
