# Generated by Django 5.2.12 on 2026-03-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0003_rename_modified_at_reservation_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ridealert",
            name="departure_datetime",
        ),
        migrations.AddField(
            model_name="ridealert",
            name="after_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ridealert",
            name="before_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                    ("cancelled_by_driver", "Cancelled by the driver"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
