# Generated by Django 5.2.12 on 2026-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0005_reservation_status_alter_reservation_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                    ("payment_disabled", "Payment Disabled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
