# Generated by Django 5.2.12 on 2026-03-27 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0006_alter_reservation_payment_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("available_seats__gte", 1), ("available_seats__lte", 10)
                ),
                name="available_seats_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="ride",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_per_seat__gte", 1)), name="price_positive"
            ),
        ),
    ]
