# Generated by Django 5.2.12 on 2026-03-27 21:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0007_ride_available_seats_range_ride_price_positive"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ride",
            name="available_seats_range",
        ),
        migrations.AddConstraint(
            model_name="ride",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("available_seats__gte", 0), ("available_seats__lte", 10)
                ),
                name="available_seats_range",
            ),
        ),
    ]
