# Generated by Django 5.2.12 on 2026-04-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0008_remove_ride_available_seats_range_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="arrival_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
