# Generated by Django 5.2.12 on 2026-04-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carpool", "0009_ride_arrival_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="reminder_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="riderequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("cancelled_by_driver", "Cancelled by the driver"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
